database:
    type: postgres
    database: infect
    schema: rda_lock_service
    hosts:
        - host: 10.80.100.1
          username: postgres
          password: ${LOCK_SERVICE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20



service-registry:
    host: ${SERVICE_REGISTRY_HOST}