database:
    type: postgres
    database: infect
    schema: rda_lock_service
    hosts:
        - host: ${LOCK_SERVICE_DB_HOST}
          username: ${LOCK_SERVICE_DB_USER}
          password: ${LOCK_SERVICE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20


service-registry:
    host: http://l.dns.porn:9000